@FinTrack.API_HostAddress = http://localhost:5062

GET {{FinTrack.API_HostAddress}}/weatherforecast/
Accept: application/json

###

### Generate demo data
POST {{FinTrack.API_HostAddress}}/api/Seed/generate-demo-data

###
